name: VamTimelinePackage

on:
  push:
    tags: 
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Zip the release package
      id: zip
      run: zip -r "VamTimeline.zip" "./src" -x "*.csproj"
    - name: GitHub release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: VamTimeline.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
