name: VamTimelinePackage

on:
  push:
    tags: 
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Zip the release package
      id: zip
      run: zip -r "VamTimeline.${VERSION}.zip" "./src" -x "*.csproj"
    - name: GitHub release
      uses: softprops/action-gh-release@v0.1.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: VamTimeline.${VERSION}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
